name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [ "smoke", "unit", "integration", "regression" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (${{ matrix.group }})
        run: |
          case "${{ matrix.group }}" in
            smoke) pytest -m "smoke" -n auto ;;
            unit) pytest tests/unit -n auto --cov=app --cov-report=xml ;;
            integration) pytest -m "integration" -n auto ;;
            regression) pytest -m "regression" -n auto ;;
          esac

      - name: Upload coverage (unit job only)
        if: matrix.group == 'unit'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
